
[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" }
]

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
